name: Documentation

on:
  workflow_call:
    inputs:
      ruby-version:
        description: 'Ruby version to use'
        required: false
        default: '3.3'
        type: string
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Remove .gitmodules if exists
      run: |
        if [ -f .gitmodules ]; then
          git rm --cached .gitmodules || true
          rm .gitmodules || true
        fi

    - name: Clean up submodule references
      run: |
        git submodule deinit -f --all || true
        git config --remove-section submodule.Example/calendar_app || true
        rm -rf .git/modules/Example/calendar_app || true

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'

    - name: Install dependencies
      run: |
        rm -f doc/created.rid
        rm -rf doc docs _site rdoc
        bundle install
        gem install rdoc

    - name: Generate RDoc
      run: |
        bundle exec rdoc --exclude Example/calendar_app --op doc --force-update

    - name: Debug Deployment
      run: |
        echo "Current directory:"
        pwd
        echo "Contents of doc/:"
        ls -la doc/

    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'doc/'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

    - name: Output URL
      run: echo "Deployed to ${{ steps.deployment.outputs.page_url }}"
